export enum KeyboardKeys {
  KeyA = 'a',
  KeyB = 'b',
  KeyC = 'c',
  KeyD = 'd',
  KeyE = 'e',
  KeyF = 'f',
  KeyG = 'g',
  KeyH = 'h',
  KeyI = 'i',
  KeyJ = 'j',
  KeyK = 'k',
  KeyL = 'l',
  KeyM = 'm',
  KeyN = 'n',
  KeyO = 'o',
  KeyP = 'p',
  KeyQ = 'q',
  KeyR = 'r',
  KeyS = 's',
  KeyT = 't',
  KeyU = 'u',
  KeyV = 'v',
  KeyW = 'w',
  KeyX = 'x',
  KeyY = 'y',
  KeyZ = 'z',

  Digit0 = 'digit0',
  Digit1 = 'digit1',
  Digit2 = 'digit2',
  Digit3 = 'digit3',
  Digit4 = 'digit4',
  Digit5 = 'digit5',
  Digit6 = 'digit6',
  Digit7 = 'digit7',
  Digit8 = 'digit8',
  Digit9 = 'digit9',

  Space = 'space',
  Enter = 'enter',
  Tab = 'tab',
  Escape = 'escape',
  Backspace = 'backspace',

  Shift = 'shift',
  ControlLeft = 'controlleft',
  ControlRight = 'controlright',
  Alt = 'alt',
  AltRight = 'altright',

  ArrowLeft = 'arrowleft',
  ArrowUp = 'arrowup',
  ArrowRight = 'arrowright',
  ArrowDown = 'arrowdown',

  F1 = 'F1',
  F2 = 'F2',
  F3 = 'F3',
  F4 = 'F4',
  F5 = 'F5',
  F6 = 'F6',
  F7 = 'F7',
  F8 = 'F8',
  F9 = 'F9',
  F10 = 'F10',
  F11 = 'F11',
  F12 = 'F12',
}
